### ISSUE TITLE
le nom du projet

### ISSUE THREAD

**Issue by HatefulRock** [ManuSerp/GRANE-WEB#5]
slt tu peux trouver un nom plus style genre deep-grane-web ou un truc comme ca stp merci

**Comment by ManuSerp** [comment]
> slt tu peux trouver un nom plus style genre deep-grane-web ou un truc comme ca stp merci

Yes sorry that is just a temporary name, the true name will be way cooler

**Comment by HatefulRock** [comment]
ok thx
